### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by xabgesagtx** [surplustv/plugin.video.meanstv#22]
means.tv allows to search it's content. Currently, the plugin only allows to navigate through the content, which requires to know, where the content is located.

It would be more convenient for the user to have the same comfort of search as in the apps and the website

**Comment by czoller** [comment]
Good idea. Do you know any good example of another Kodi addon that contains a search?

**Comment by xabgesagtx** [comment]
Some example would be:
* https://github.com/anxdpanic/plugin.video.youtube
* https://github.com/CastagnaIT/plugin.video.netflix/
