### ISSUE TITLE
Rename Kodi addon to just "Means.TV" instead of "Means TV Kodi Plugin"

### ISSUE THREAD

**Issue by czoller** [surplustv/plugin.video.meanstv#30]
It looks a bit unusual the way it is now and it's obvious that it is a Kodi Plugin, it doesn't have to say it in it's name.

**Comment by czoller** [comment]
@xabgesagtx: What do you think?

**Comment by czoller** [comment]
The addon description might also be improved.

**Comment by xabgesagtx** [comment]
Totally agree. Should be renamed before publishing
